baseURL = "https://snnmst.netlify.app/"
relativeURLs = true
canonifyURLs = true
languageCode = 'en-us'
title = "sinan's blog"
theme = 'PaperMod'
[pagination]
  pagerSize = 5


[params]
  author = "Sinan Mustu"
  description = "Personal Blog Page"
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  homeInfoParams = false
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowsocialIcons = true

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/sinanmustu"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/snnmst"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1