baseURL = "https://snnmst.netlify.app/"
relativeURLs = true
canonifyURLs = true
languageCode = 'en-us'
title = "sinan's blog"
theme = 'PaperMod'
[pagination]
  pagerSize = 5

[params]
  author = "Sinan Mustu"
  description = "Personal Blog Page"
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  homeInfoParams = false
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false